### ISSUE TITLE
Disorder checklist

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/refugee#1]
# AnySurfer Checklist

This list need to be checked before releasing `v1.0.0-rc`
## 1 Navigatie
- [ ] `1.1` Website is bruikbaar met het toetsenbord. 
- [ ] `1.2` Linkteksten zijn betekenisvol binnen hun context. 
## 2 Inhoud
- [ ] `2.1` Broncode voldoet aan de specificatie. 
### 2.2 Tekst
- [ ] `2.2.1` Pagina's hebben een betekenis volle titel. 
- [ ] `2.2.2` Pagina's zijn semantisch gestructureerd. 
- [ ] `2.2.3` Basistaal van iedere pagina is aangegeven.
### 2.3 Afbeeldingen
- [ ] `2.3.1` Elke afbeelding heeft een alt-attribuut.
- [ ] `2.3.2` Complexe afbeeldingen zijn tekstueel beschreven. 
- [ ] `2.3.3` Informatiedragende achtergrondafbeeldingen hebben een alternatief. 
### 2.4 Gegevenstabellen
- [ ] `2.4.1` Tabel is bruikbaar na linearisatie. 
- [ ] `2.4.2` Tabelhoofdingen zijn gemarkeerd met een th-element. 
- [ ] `2.4.3` Bijschrift is gemarkeerd met het caption-element.
- [ ] `2.4.4` Complexe tabellen zijn gemarkeerd met headers-attributen.
### 2.5 Video en geluid
- [ ] `2.5.1` Video en geluid zijn benoemd. 
- [ ] `2.5.2` Tekstversie is beschikbaar.
- [ ] `2.5.3` Video is ondertiteld. 
- [ ] `2.5.4` Geluid start niet automatisch. 
### 3.1 tekstopmaak
- [ ] `3.1.1` Links zijn zichtbaar te onderscheiden. 
- [ ] `3.1.2` Spaties en andere tekens worden niet gebruikt voor vormgeving.
### 3.2 Paginaopmaak
- [ ] `3.2.1` Pagina-inhoud heeft een betekenisvolle volgorde. 
- [ ] `3.2.2` (i)Frames hebben een beschrijvende naam en titel. 
### 3.3 Beweging
- [ ] `3.3.1` Tekst en afbeeldingen knipperen niet meer dan 3 keer per seconde. 
- [ ] `3.3.2` Beweging kan gestopt worden. 
### 3.4 Kleur en andere visuele informatie.
- [ ] `3.4.1` Inhoud is begrijpelijk voor wie geen kleuren kan onderscheiden.
### 4.1 Formulieren
- [ ] `4.4.1` Labels en formuliervelden zijn verbonden. 
- [ ] `4.1.2` Velden zonder zichtbaar label hebben een beschrijvende tooltip. 
- [ ] `4.1.3` Het label bij datumvelden vermeldt de vereiste notatie. 
- [ ] `4.1.4` Samenhorende formuliervelden zijn ingesloten door een fieldset. 
- [ ] `4.1.5` Samenhorende onderdelen in een keuzelijst zijn ingesloten door een optgroup. 
- [ ] `4.1.6` Verplichte velden zijn binnen het label aangekondigd. 
- [ ] `4.1.7` Ieder formulier heeft een zichtbare verzendknop. 
- [ ] `4.1.8` Bij het valideren wordt foutieve invoer gemarkeerd en tekstueel toegelicht. 
### 4.2 Tijdslimieten
- [ ] `4.2.1` Acties zijn niet strikt tijdsgebonden. 
### 4.x Varia
- [ ] `4.3` De automatische actualisatie van paginaonderdelen kan stopgezet worden. 
- [ ] `4.4` Verwittig de bezoekers bij paginawijzigingen. 
- [ ] `4.5` Pop-ups verschijnen niet automatisch.
